/* libhop — the Hop client SDK + bearer contract. GENERATED by cbindgen; do not edit. */

#ifndef HOP_H
#define HOP_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Aggregate cap for variable-length byte slices crossing the C boundary. Larger application bodies
// must be chunked by the caller; fixed-width keys use tighter per-call caps below.
#define MAX_C_ABI_INPUT_BYTES ((16 * 1024) * 1024)

// Byte length written by [`hop_validate_wire_bundle`]. The layout is documented on that function.
#define HOP_WIRE_BUNDLE_METADATA_LEN 211

// The libhop C-ABI version. Bump on any signature or semantic change to an exported `hop_*`
// function. A wrapper should assert `hop_abi_version() == HOP_ABI_VERSION` at load so a wrapper
// built against a newer header fails loudly instead of drifting silently (F-28). This is the
// *ABI* version and is independent of the *wire* format version (bundle.rs `BUNDLE_VERSION`).
#define HOP_ABI_VERSION 4

// Which side opened a bearer link (the Noise role). Mirrors hop-core's internal `Role`.
typedef enum HopLinkRole {
    // We dialed out (BLE central / TCP connect / Wi-Fi inviter) → Noise initiator.
    HopLinkRole_Dialer = 0,
    // A peer connected in (peripheral / listener / invitee) → Noise responder.
    HopLinkRole_Acceptor = 1,
} HopLinkRole;

// A running Hop node the host drives. Thread-safe (interior `Mutex`), handed to
// the foreign side as a reference-counted object.
typedef struct HopNode HopNode;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the ABI version this shared library implements (see [`HOP_ABI_VERSION`]).
uint32_t hop_abi_version(void);

// Decode, verify, and canonically re-encode one complete bundle without constructing protocol state.
// On success, writes exactly [`HOP_WIRE_BUNDLE_METADATA_LEN`] bytes to `out_metadata`:
// `[version:1, destination:1, private:1, is_ack:1, wire_len_le:4, ciphertext_len_le:4,
// copies_le:2, hops:1, trace_len:1, created_at_le:8, lifetime_ms_le:4, hop_limit:1,
// id:32, private_content_id:32, recognition_tag:16, recognition_ephemeral:32,
// mailbox_present:1, mailbox:2, integrity_kind:1, signature_len_le:2, signature:64]`.
// `integrity_kind` is 0 for an Ed25519-signed bundle, 1 for a private wire ID, and 2 for a vaccine
// ID. Fields that do not apply are zero-filled. Returns false on invalid pointers or lengths,
// decode/verification failure, a non-canonical encoding, or an output buffer shorter than 211 bytes.
bool hop_validate_wire_bundle(const uint8_t *bytes,
                              uintptr_t len,
                              uint8_t *out_metadata,
                              uintptr_t out_metadata_len);

// Open a node with persistent storage at `db_path` (UTF-8 C string), a saved 32-byte identity
// `secret` (pass NULL/0 for a fresh identity), and a 32-byte `app_secret` (NULL/0 = open fabric).
// Returns an owning handle to free with `hop_node_free`, or NULL on a NULL/non-UTF-8 `db_path`.
//
// If the db path exists but can't be opened it is quarantined and reopened fresh; only if that
// also fails does the node run with EPHEMERAL storage (call `hop_node_is_persistent` to detect
// this) rather than silently, and rather than NULL (F-26).
const struct HopNode *hop_node_open(const char *db_path,
                                    const uint8_t *secret,
                                    uintptr_t secret_len,
                                    const uint8_t *app_secret,
                                    uintptr_t app_secret_len);

// Like `hop_node_open`, but ENCRYPTS the store at rest with a raw `key` (typically 32 bytes) the host
// derives and stores in the platform Keychain/Keystore (F-25). Real encryption requires libhop to be
// built with the store's `sqlcipher` feature; otherwise the key is accepted but the db stays plain.
// A NULL/empty key behaves like `hop_node_open`. NULL/non-UTF-8 `db_path` ⇒ NULL.
const struct HopNode *hop_node_open_keyed(const char *db_path,
                                          const uint8_t *secret,
                                          uintptr_t secret_len,
                                          const uint8_t *app_secret,
                                          uintptr_t app_secret_len,
                                          const uint8_t *key,
                                          uintptr_t key_len);

// Create a node with a fresh identity and ephemeral (in-memory) storage. Free with `hop_node_free`.
const struct HopNode *hop_node_new(void);

// Open a node from a saved 32-byte identity `secret` with ephemeral (in-memory) storage. Pass
// NULL/0 for a fresh identity. Free with `hop_node_free`.
const struct HopNode *hop_node_with_secret(const uint8_t *secret, uintptr_t secret_len);

// Whether this node has durable storage. Returns false when the db path was unusable and the
// node is running ephemerally (state will not survive a restart) — the host should surface this
// rather than treat the database as ground truth (F-26). NULL handle ⇒ false.
bool hop_node_is_persistent(const struct HopNode *node);

// How many persisted records failed to decode on startup (F-03). Non-zero ⇒ an upgrade changed
// a struct's on-disk layout and dropped that state; surface it to the user. NULL handle ⇒ 0.
uint32_t hop_node_rehydrate_dropped(const struct HopNode *node);

// Free a node handle returned by any constructor. Safe to pass NULL.
//
// Ownership: this consumes the one strong reference each constructor returned. The caller must
// ensure no other thread is calling into the same handle concurrently with free (the ABI does
// not expose a retain/clone), and must not use the pointer afterward.
void hop_node_free(const struct HopNode *node);

// Write this node's 32-byte address into `out` (must have room for 32 bytes). False on NULL.
bool hop_node_address(const struct HopNode *node, uint8_t *out);

// Write this node's 32-byte identity secret into `out` (room for 32 bytes) so the host can persist
// it (e.g. in the Keychain) and restore the node later with `hop_node_with_secret`/`hop_node_open`.
// Returns the number of bytes written (32), or 0 on NULL.
uintptr_t hop_node_secret(const struct HopNode *node, uint8_t *out);

// Set the display name this node reports via presence / `hop.identify` (DESIGN.md §29).
void hop_node_set_name(const struct HopNode *node, const char *name);

// Advance authenticated protocol time: expire adverts, retransmit unacked bundles, and prune dedup.
// `now_ms` must be plausible, non-regressing Unix epoch milliseconds from synchronized wall time.
// Monotonic uptime counters such as Arduino `millis()` or `esp_timer_get_time()` are not Unix time.
void hop_node_tick(const struct HopNode *node, uint64_t now_ms);

// A bearer link came up. `role` = which side dialed (the Noise initiator/responder selector),
// using the [`HopLinkRole`] discriminants (0 = Dialer, 1 = Acceptor).
//
// core-ffi-05: `role` is taken as a plain `u32`, not the `HopLinkRole` enum by value. A C caller
// passing an out-of-range int would otherwise materialize an invalid Rust enum (instant UB) before
// any validation runs. Here only `0` selects Dialer; any other value is treated as Acceptor, so a
// bad int can never be UB.
void hop_link_up(const struct HopNode *node, uint64_t link, uint32_t role);

// One frame of opaque bytes arrived on `link`.
void hop_bytes_received(const struct HopNode *node,
                        uint64_t link,
                        const uint8_t *data,
                        uintptr_t len);

// A bearer link dropped.
void hop_link_down(const struct HopNode *node, uint64_t link);

// Drain queued outbound packets. Synchronously invokes `sink(ctx, link, bytes_ptr, bytes_len)`
// once per packet during this call — this is the POLL model; core never pushes asynchronously.
// The byte pointer is valid only for the duration of each `sink` call; copy what you keep.
void hop_drain_outgoing(const struct HopNode *node, void (*sink)(void *ctx,
                                                                 uint64_t link,
                                                                 const uint8_t *bytes,
                                                                 uintptr_t len), void *ctx);

// Subscribe the directory to a service `topic` (UTF-8 C string).
void hop_subscribe(const struct HopNode *node, const char *topic);

// Publish this node's prekey advert (DESIGN.md §25) so peers can seal forward-secret messages to
// us; it gossips on link-up. Call once after opening (and after the first `hop_node_tick` sets a
// real clock, else the advert is judged expired). Returns true on success.
bool hop_publish_prekey(const struct HopNode *node);

// Drain newly-received messages (poll model). Invokes
// `sink(ctx, inbox_id32, from32, content_type_cstr, body_ptr, body_len, hops, created_at_ms)` once
// per message during this call. `inbox_id` and `from` each point at 32 bytes; `content_type` is a
// NUL-terminated UTF-8 string; `body` is `body_len` bytes. All pointers are valid only for the
// callback. Returning true is synchronous host acceptance: core then durably removes that item and
// emits its ACK/vaccine. Returning false, exiting, or failing acceptance persistence leaves it queued
// for redelivery.
void hop_poll_inbox(const struct HopNode *node,
                    bool (*sink)(void *ctx,
                                 const uint8_t *inbox_id,
                                 const uint8_t *from,
                                 const char *content_type,
                                 const uint8_t *body,
                                 uintptr_t body_len,
                                 uint8_t hops,
                                 uint64_t created_at),
                    void *ctx);

// Durably accept one item previously returned by [`hop_poll_inbox`]. `inbox_id` points to exactly
// 32 bytes. Returns false for NULL, an unknown/already-accepted id, or a persistence failure.
bool hop_accept_inbox(const struct HopNode *node, const uint8_t *inbox_id);

// Send to a DIRECTLY-CONNECTED peer `dst` (32 bytes), sealed with the key learned at handshake
// (the directed §27 path; prefer `hop_send_message` unless you specifically want a directed send).
// On success writes the 32-byte bundle id to `out_id` (may be NULL) and returns true; false if not
// connected to that peer or on error.
bool hop_send_to(const struct HopNode *node,
                 const uint8_t *dst,
                 const char *content_type,
                 const uint8_t *body,
                 uintptr_t body_len,
                 bool request_ack,
                 uint8_t *out_id);

// Delivery status of a message we sent, by its 32-byte bundle `id`. Writes each field to its
// (nullable) out-param: `relayed` = distinct peers handed a copy; `delivered` = destination
// confirmed; `hops`/`ms` = the FORWARD-path (A→B) length + latency the destination reported (§39
// private ACK), 0 until delivered. Returns false on NULL node/id.
bool hop_message_status(const struct HopNode *node,
                        const uint8_t *id,
                        uint32_t *out_relayed,
                        bool *out_delivered,
                        uint8_t *out_hops,
                        uint32_t *out_ms);

// True iff messaging `addr` (32 bytes) is forward-secret — a ratchet session exists (DESIGN.md §25)
// rather than a static seal. Drives a lock indicator. False on NULL.
bool hop_is_secured(const struct HopNode *node,
                    const uint8_t *addr);

// Send a hops:// service request to `dst` (32 bytes): invoke `method` on `service` with `args`.
// The reply arrives later via `hop_poll_service_responses`. Writes the 32-byte request id to
// `out_id` (may be NULL) and returns true.
bool hop_send_service_request(const struct HopNode *node,
                              const uint8_t *dst,
                              const char *service,
                              const char *method,
                              const uint8_t *args,
                              uintptr_t args_len,
                              uint8_t *out_id);

// Seal a hops:// response back to a request's caller (host side). `to` = the request's `from`;
// `for_request_id` = its `request_id`. Returns true on success.
bool hop_send_service_response(const struct HopNode *node,
                               const uint8_t *to,
                               const uint8_t *for_request_id,
                               uint16_t status,
                               const uint8_t *body,
                               uintptr_t body_len);

// Join the endpoint cluster keyed by the 32-byte `secret` (all replicas of one endpoint pass the
// same secret). `hop_send_service_response` marks a request complete for the siblings automatically;
// a fire-and-forget handler calls `hop_cluster_mark_done`. No-op if `secret` is null.
void hop_cluster_join(const struct HopNode *node,
                      const uint8_t *secret);

// Join the endpoint cluster from a passphrase (the 32-byte secret is derived from it): every replica
// given the same string joins the same cluster, across languages and the standalone service. This is
// the ergonomic entry point; `hop_cluster_join` takes a raw 32-byte secret. No-op if `pass` is null.
void hop_cluster_join_passphrase(const struct HopNode *node,
                                 const uint8_t *pass,
                                 uintptr_t pass_len);

// Explicit completion for a fire-and-forget handler (one that sends no response): mark request
// `(from32, request_id32)` handled and gossip it so sibling replicas drop their copies.
void hop_cluster_mark_done(const struct HopNode *node,
                           const uint8_t *from,
                           const uint8_t *request_id);

// Whether request `(from32, request_id32)` would be dropped as already handled by a sibling replica
// (introspection; the poll path applies this automatically). False if `node` is null or unclustered.
bool hop_cluster_would_drop(const struct HopNode *node,
                            const uint8_t *from,
                            const uint8_t *request_id);

// Live replica count (self + peers within the membership TTL); 1 if not clustered, 0 if `node` null.
uint32_t hop_cluster_members(const struct HopNode *node);

// Require at least `min_live_members` recently visible before processing. This TTL-based threshold
// is a conservative failover heuristic, not consensus or an at-most-once guarantee. `0` disables it.
void hop_cluster_set_quorum(const struct HopNode *node,
                            uint32_t min_live_members);

// Drain hops:// service requests addressed to this node (host side). Invokes
// `sink(ctx, from32, request_id32, service_cstr, method_cstr, args_ptr, args_len)` per request.
void hop_poll_service_requests(const struct HopNode *node,
                               void (*sink)(void *ctx,
                                            const uint8_t *from,
                                            const uint8_t *request_id,
                                            const char *service,
                                            const char *method,
                                            const uint8_t *args,
                                            uintptr_t args_len),
                               void *ctx);

// Poll hops:// service responses sealed back to this node (caller side). Invokes
// `sink(ctx, from32, for_request_id32, status, body_ptr, body_len)` per response. Returning true is
// synchronous acceptance. Returning false leaves the durable row queued for redelivery until
// [`hop_accept_service_response`] succeeds.
void hop_poll_service_responses(const struct HopNode *node,
                                bool (*sink)(void *ctx,
                                             const uint8_t *from,
                                             const uint8_t *for_request_id,
                                             uint16_t status,
                                             const uint8_t *body,
                                             uintptr_t body_len),
                                void *ctx);

// Durably accept one response previously returned by [`hop_poll_service_responses`].
// `request_id` is the 32-byte `for_request_id` supplied to the callback. Returns false for NULL, an
// unknown/already-accepted request id, or a persistence failure.
bool hop_accept_service_response(const struct HopNode *node, const uint8_t *request_id);

// Encode a 32-byte `addr` as base58 into the C buffer `out` (`out_cap` bytes incl. NUL). Returns
// the string length (excluding NUL), or 0 on NULL / insufficient capacity.
uintptr_t hop_address_to_base58(const uint8_t *addr, char *out, uintptr_t out_cap);

// Decode a base58 address C string `text` into `out32` (32 bytes). Returns true iff it decoded to
// exactly 32 bytes.
bool hop_address_from_base58(const char *text, uint8_t *out32);

// Send a message to the 32-byte address `dst` — untraceable by default (DESIGN.md §39).
// `content_type` is a UTF-8 C string (e.g. "text/plain"); `body`/`body_len` is the payload. If
// `request_ack`, a private delivery confirmation is requested. On success writes the 32-byte
// bundle id into `out_id` (room for 32 bytes, may be NULL to ignore) and returns true.
bool hop_send_message(const struct HopNode *node,
                      const uint8_t *dst,
                      const char *content_type,
                      const uint8_t *body,
                      uintptr_t body_len,
                      bool request_ack,
                      uint8_t *out_id);

// Sign a self-certifying reachability record for THIS node's address, binding it to `endpoint`
// (UTF-8 C string, e.g. "wss://myaddress.com/_hop") for `ttl_secs`. Invokes `sink(ctx, bytes, len)`
// once with the signed record bytes (serve at /.well-known/hop or gossip). No-op on NULL args.
void hop_sign_reach_record(const struct HopNode *node,
                           const char *endpoint,
                           uint32_t ttl_secs,
                           void (*sink)(void *ctx, const uint8_t *bytes, uintptr_t len),
                           void *ctx);

// Verify a reachability record. `now_secs` = current Unix time to enforce expiry (0 skips the expiry
// check). Returns true iff valid; on a valid record invokes `sink(ctx, address32, endpoint_cstr,
// issued_at, ttl_secs)` once. Self-certifying: the record is checked against the address it names,
// no external anchor. `bytes`/`len` is the record from `hop_sign_reach_record`.
bool hop_verify_reach_record(const uint8_t *bytes,
                             uintptr_t len,
                             uint64_t now_secs,
                             void (*sink)(void *ctx,
                                          const uint8_t *address,
                                          const char *endpoint,
                                          uint64_t issued_at,
                                          uint32_t ttl_secs),
                             void *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HOP_H */
